#!/bin/bash
echo Making symlinks for blogpost and fake source highlight...
ln -s $PWD/src/blogpost/blogpost.py /usr/bin/blogpost
ln -s $PWD/src/fake-source-highlight/fake-source-highlight.py /usr/bin/source-highlight
echo Creating ~/.blogpost config files...
mkdir ~/.blogpost
cp src/blogpost/conf/blogpost_example.conf ~/.blogpost/blogpost.conf
cp src/blogpost/conf/tidy.conf ~/.blogpost/tidy.conf
echo Installing asciidoc wordpress backend...
asciidoc --backend install src/blogpost/conf/wordpress.zip
echo Done!
echo Don\'t forget to edit blog URL, username and password in ~/.blogpost...

