CentOS 6: Install Samba
=======================
Lance Gatlin <lance.gatlin@gmail.com>
v1, 20-Apr-2013
:blogpost-status: unpublished
:blogpost-categories: centos6,windows7,samba

== Versions
1. CentOS 6.4
2. Samba 3.6.9
3. Windows 7

== Install
[source,sh,numbered]
sudo yum install samba

=== Configure

1. Add linux user for samba access:
+
NOTE: Substitute $SAMBA_USER for samba username
+
[source,sh,numbered]
----
sudo useradd $SAMBA_USER
----
+
2. Set linux user password:
+
[source,sh,numbered]
sudo passwd $SAMBA_USER
+
3. Add linux user to samba (use same password)
+
[source,sh,numbered]
sudo smbpasswd -a $SAMBA_USER
sudo smbpasswd -e $SAMBA_USER
+
4. Optional: Add a path to share and change ownership to samba user:
+
NOTE: Substitute $PATH with the absolute path to the directory to share
+
[source,sh,numbered]
mkdir $PATH
chown -R $SAMBA_USER:$SAMBA_USER $PATH
+
NOTE: home directories are shared by the default samba config
+
5. Optional: Set selinux context for directory to "samba_share_t" to permit sharing:
+
[source,sh,numbered]
sudo chcon -t samba_share_t $PATH
+
6. Optional: Set selinux bool to make home directories shareable:
+
[source,sh,numbered]
sudo setsebool -P samba_enable_home_dirs on
+
7. Edit /etc/samba/smb.conf and change the workgroup to match the Windows 7 workgroup:
+
NOTE: Substitute $WG with the name of the workgroup
+
[source,text,numbered]
----
        workgroup = $WG
----
+
NOTE: if not configured, Windows 7 defaults to the workgroup name "workgroup"
+
8. Add the following to the end of /etc/samba/smb.conf:
+
NOTE: Substitute $SHARE_NAME with the name of the share
+
[source,text,numbered]
----
[$SHARE_NAME]
       path = $PATH
       writeable = yes
       browseable = yes
       valid users = $SAMBA_USER
----
+
9. Start services
+
[source,sh,numbered]
sudo service smb start
sudo service nmb start
+
10. Start on boot
+
[source,sh,numbered]
sudo chkconfig smb on
sudo chkconfig nmb on
+
11. Open the following ports for samba:
  ** 137 udp
  ** 138 udp
  ** 139 tcp
  ** 445 tcp
+
See http://lancegatlin.org/tech/centos-6-open-a-port-for-iptables[Open a port for iptables]

== Test
1. On Windows 7, open command-line and map drive:
+
NOTE: Substitute $HOSTNAME for the hostname of the samba machine, $PASSWORD with the password of the samba user
+
[source,text,numbered]
net use z: \\$HOSTNAME\$SHARE_NAME /user:$SAMBA_USER $PASSWORD
+
[NOTE]
====
It may be necessary to run
[source,text,numbered]
----
net use * /delete
----
to remove active connections and clear cached connection information if you have attempted to connect to the CentOS machine before.
====
